### PR TITLE
MatrixMate support added

### PR DESCRIPTION
**Pull request by DTesch-Reem**
Added Support for the MatrixMate
Kind of a quick and dirty fix because I'm not that experienced with Craft plugin development

### CODE REVIEW

**Comment by timmyomahony** [comment]
Thanks for adding this, I'm going to be reviewing week.

**Comment by angelokeirsebilck** [comment]
Any updates on this?

**Comment by timmyomahony** [comment]
I've been working on making some Neo and Supertable fixes this week, so will be working on this next.

**Comment by thomascoppein** [comment]
Any update?

**Comment by mtwalsh** [comment]
@timmyomahony I've just started using this plugin on a project but it doesn't seem to play nicely with MatrixMate, so we have to wave goodbye to all our MatrixMate tabs. Is this PR close to being merged in?

**Comment by timmyomahony** [comment]
Cool, so just to confirm @mtwalsh, in your case, you would be happy with just the button being available? The modal overlay would continue to appear according to the Matrix Field Preview configuration, and wouldn't need to mimic the MatrixMate configuration.

**Comment by mtwalsh** [comment]
@timmyomahony Yes, that's right I appreciate we'd have to double up our categorisation of the Matrix blocks in both plugins. But crucially the tabs we setup in MatrixMate when actually authoring content within a Matrix block would still work? As I think this did not when I last tested the plugin in combination with MatrixMate.

**Comment by timmyomahony** [comment]
Yes, so the tabs would still work, as would the regular MatrixMate field. There would just be the addition of the "content preview" button for the Matrix Field Preview modal overlay on the right. 

CleanShot 2023-10-03 at 16 43 47@2x

**Comment by mtwalsh** [comment]
@timmyomahony Sounds great 👍

**Comment by timmyomahony** [comment]
I've added basic MatrixMate support now in release `4.1.0`. Try it out and let me know if everything is working OK. This is just basic support, as discussed above. 

I'm going to close this PR, as it's addressing the issue in a different way, but thanks for the work @DTesch-Reem. If people want the ability to override the ordering and categorisation of the Matrix Field Preview modal with MatrixMate settings, then we can open a different PR/issue to handle that.

**Comment by mtwalsh** [comment]
Great news, thanks for sorting this @timmyomahony. Will let you know if we hit any issues.

**Pull request closed without merging**
